[template.environment]
  SHORTCUTS_NAME = "Your name"
  SHORTCUTS_SITE = "Your personal site"
  SHORTCUTS_TWITTER = "Your Twitter username"
  SHORTCUTS_YOUTUBE = "Your YouTube URL"
  SHORTCUTS_GITHUB = "Your GitHub username"
  SHORTCUTS_LINKEDIN = "Your LinkedIn url"
  SHORTCUTS_DEVTO = "Your Dev.to username"
  SHORTCUTS_MEDIUM = "Your Medium url"
[build]
  command   = "npm run build"
  publish   = "public"